server:
  port: 6000

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:5000/uaa/oauth/token
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current


auth-service:
  url: http://localhost:5000

statistics-service:
  url: http://localhost:7000